### ISSUE TITLE
Support for new GPU instances (G4)

### ISSUE THREAD

**Issue by acap4z** [c6fc/npk#15]
Hi there,

Some time ago I proposed a way to include the new G4 instances to NPK since they were more cost effective as a pull request in the old repo: [https://github.com/Coalfire-Research/npk/pull/140](https://github.com/Coalfire-Research/npk/pull/140)

The PR was incomplete so it couldn't be merged, but maybe we could resume this task. I could do it myself with some guidance about how to fully implement new instance types (which files need to be modified). #

**Comment by c6fc** [comment]
The next update is slated to add non-US region support and to enable the newer GPU instances.

**Comment by c6fc** [comment]
Support for g4 and p4 instances has been pushed to dev branch in b22985e

If you get a chance to test it, I'd love some feedback.

**Comment by c6fc** [comment]
It's there now!
