### ISSUE TITLE
NPK Deployment / Upgrade Issue

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#25]
Getting prompted with below when trying to deploy / upgrade NPK with latest commit. Do I need to specify anything when prompted or is this a bug?

var.dictionary-us-east-1
  Enter a value:

var.dictionary-us-east-1-id
  Enter a value:

**Comment by c6fc** [comment]
Yeah. Delete `npk/terraform/dictionaries.auto.tfvars`.

I had a line in the old deployment script that told Git to ignore any changes to that file, and that setting persists new pulls. It only comes up if you've self-hosted before and are still using the same folder. If you delete the folder and re-pull, this will also go away.

**Comment by bzekanovic** [comment]
Did not resolve the issue since I get error message below

root@422c2db62a68:/npk/terraform# npm run deploy

> npk_community@2.6.0 deploy /npk/terraform
> node index.js && `cat .ENVVARS` && terraform init -force-copy && terraform apply -auto-approve

/npk/terraform/index.js:289
					regionQuotas[region] ??= {};
					                     ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npk_community@2.6.0 deploy: `node index.js && `cat .ENVVARS` && terraform init -force-copy && terraform apply -auto-approve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the npk_community@2.6.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-16T16_45_03_673Z-debug.log

**Comment by c6fc** [comment]
Make sure you're using the right version of Node.

`nvm install 17.0.1 && nvm use 17.0.1`
