### ISSUE TITLE
NPK Deployment / Custom Domain Issue

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#27]
I'm deploying NPK with custom domain and npk-settings.json configs are ignored and NPK is deployed with default Cloudfront domain. Let me know if there is anything below that could could cause issue and I am on latest release of NPK. 

{
  "backend_bucket": "npk-terraform-quickdeploy-<BUCKETNAME>",
  "campaign_data_ttl": 604800,
  "georestrictions": ["US", "CA", "GB"],
  "campaign_max_price": 50,
  "useCustomDNS": true,
  "route53Zone": "<ROUTE53ZONEID>",
  "dnsNames": {
    "www": [
      "<DOMAIN NAME>"
    ],
    "api": [
      "<DOMAIN NAME>"
    ]
  },
 "awsProfile": "default",
 "criticalEventsSMS": "<PHONE NUMBER>",
 "adminEmail": "<ADMIN EMAIL>",
 "useSAML": true,
 "sAMLMetadataFile": "/npk/NPK.xml"
}

**Comment by notabotscott** [comment]
How did you resolve this? I am getting an error when trying to configure these options.

```
[!] Invalid setting key [useCustomDNS] in npk-settings.json
[!] Invalid setting key [dnsNames] in npk-settings.json
```

**Comment by c6fc** [comment]
> How did you resolve this? I am getting an error when trying to configure these options.
> 
> ```
> [!] Invalid setting key [useCustomDNS] in npk-settings.json
> [!] Invalid setting key [dnsNames] in npk-settings.json
> ```

Please don't necro old issues. These settings are long deprecated. If you need help, create a new issue or ask on Discord.
