### ISSUE TITLE
Less is not installed on base image, causing quickdeploy.sh to fail

### ISSUE THREAD

**Issue by 0x42424242** [c6fc/npk#28]
I pulled the latest docker image (at the time of this issue) and attempted to run the quick deploy script. I received the following error message. 

`[!] The provided profile is not valid. Try again.`

Debugging the script, the cause is this line; 

`aws --profile $profile sts get-caller-identity > /dev/null`

Attempting this in isolation results in the following error. 

```
npm run deployroot@5290a070ec47:~/npk/terraform# aws sts get-caller-identity

[Errno 2] No such file or directory: 'less': 'less'
```

The root cause is AWS CLI requires `less` to be installed. Performing an `apt-get update` and `apt-get install less` resolves the issue. Can we get this integrated into the base image? 

Cheers.

**Comment by c6fc** [comment]
I've moved to CloudShell as the preferred method for installing NPK, since it removes the challenges that folks tend to have when trying to configure AWS credentials, and I don't plan to maintain the container any longer. Closing as wontfix.
