### ISSUE TITLE
Failed to request spot fleet. AuthFailure.ServiceLinkedRoleCreationNotPermitted

### ISSUE THREAD

**Issue by neiltylerbell** [c6fc/npk#30]
NPK build through campaign creation looked great but attempting to start a campaign resulted in a "Failed to request spot fleet" error.

Cloudwatch log group for /aws/lambda/execute_campaign showed the following authorization error after spot fleet request:

`Failed to request spot fleet. AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.`

Addressed by requesting a spot fleet service linked role for the AWS account:
`aws iam create-service-linked-role --aws-service-name spotfleet.amazonaws.com`
`aws iam create-service-linked-role --aws-service-name spot.amazonaws.com`

Campaign was successfully started after building role.

**Comment by c6fc** [comment]
This is fixed in the sonnetry branch. I'll leave this open until it's merged into master.

**Comment by c6fc** [comment]
It's moved to dev. Should move to main tomorrow.

**Comment by c6fc** [comment]
Fixed in [9265d45](https://github.com/c6fc/npk/commit/9265d454d1758ffbc5810a6ed7abb6dc19fcf57a)
