### ISSUE TITLE
NPK CloudShell Deployment / SSO Improvement

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#39]
When deploying NPK with SSO XML file NPK does not save the SSO XML file in S3 bucket used to hold configs. This causes deployment to fail when next users run the NPK update as XML file is missing from CloudShell local file system. 

Is it possible to save XML file in S3 bucket used to hold NPK config?

Also, let me know if XML file is depreciated and if you have preferred process users should follow when setting up SSO. 

Thanks,

**Comment by c6fc** [comment]
That's a good callout. I'll get that fixed.

This would only apply to the sAMLMetadataFile setting. The sAMLMetadataUrl would be behave normally.

**Comment by c6fc** [comment]
Pushed to main.
