### ISSUE TITLE
Deployment / CloudShell Default Directory

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#40]
Would it be possible to use CloudShell default directory /home/cloudshell-user as a location where NPK stores all of the files as its going through deployment? I'm not sure if you had a reason on why you didn't do this initially.

**Comment by bzekanovic** [comment]
This would make it less confusing on where files are stored in case user needs to make modifications to deployment configs.

**Comment by c6fc** [comment]
I cannot, since there's not enough space there, and the size can't be increased. I can however add a line to the one-liner to dump you to `/aws/mde/npk` when it finishes if it doesn't already.

**Comment by bzekanovic** [comment]
That works for me. thx

**Comment by c6fc** [comment]
Turns out it was already set to do that, so I simply updated the README to make this more clear.
