### ISSUE TITLE
NPK Instance Type Compatibility?

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#44]
Hello, 

I've noticed that our prod NPK instance now shows Radeon Pro v520, but when selecting that instance NPK doesn't show any attack breakdown. Could it be that this instance isn't supported by NPK or is it just you don't have GPU specs integrated into NPK for this instance?
![Screen Shot 2022-04-06 at 9 08 55 PM](https://user-images.githubusercontent.com/16389468/162119406-4a5c07ec-ae51-42bb-9b9c-a44bac232176.png)

**Comment by c6fc** [comment]
Radeon is supported, and it works for most types.

When NPK shows zeroes in the performance breakdown, it means that it doesn't have numbers for that specific attack+hash type+card. I raised an issue with Hashcat when I saw that wordlists for NTLM don't work on Radeon, but just about everything else was good. What hash type were you looking at?

**Comment by bzekanovic** [comment]
I was just testing new deployment in prod with NTLM hash from Hashcat example hashes site. 

https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by c6fc** [comment]
Yeah, NTLM with wordlists on Radeon is a known incompatability in Hashcat. Stick to NVidia if you're doing NTLM.
