### ISSUE TITLE
Add link to campaign from dashboard

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#47]
1. Any way this message can be removed or updated when campaign is running "No status reports received. Nodes may have errored out" with something more accurate?
![image](https://user-images.githubusercontent.com/16389468/162212992-bb5c8073-b155-4263-9de8-0406e229501f.png)
 
2. Manage Campaigns page should also include "Start" function since right now you can only execute "Cancel / Delete" functions from that page.

3. Any way to remove hyperlink to AWS EC2 instance that is shown on dashboard and add hyperlink to related campaign?
![image](https://user-images.githubusercontent.com/16389468/162213748-1a490a0c-e04c-475b-ab8a-1e697fb08ec5.png)

**Comment by c6fc** [comment]
1. That's precisely the state of the campaign - I can hide the 'Nodes may have errored out' piece for a bit, but if you have more specific suggestions, I'm all ears.
2. This is intentional.
3. I plan to link this to the instance log. I can add a separate link to the campaign though, that's a good idea.

**Comment by c6fc** [comment]
Added in dev

**Comment by bzekanovic** [comment]
I did notice message below at first, but it did go away after I refreshed my browser page and nicer UI status metrics showed up.

![image](https://user-images.githubusercontent.com/16389468/162829008-1fa02592-aafb-4f84-85a3-3adbc4d80aa6.png)

**Comment by c6fc** [comment]
Ahh, I'd forgotten to remove a debug string. It's gone now though.

This is why dev exists :joy:

**Comment by bzekanovic** [comment]
I'll start testing this. 

Also, it would not be bad idea to show end users how to run dev branch directly from CloudShell via source <(curl https://npkproject.io/cloudshell_install_dev.sh) in your docs. I had to dig it up in your prod script, but something to mention in docs.

**Comment by c6fc** [comment]
Merged
