### ISSUE TITLE
Error processing gzip uploads

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#48]
Seems like processing large wordlist (1GB +) after uploading it via aws s3 cp s3://npk-dictionary-us-west-2-REDACTED/to_process/wordlist/ pauses after 15 minutes and doesn't resume. Is this due to lambda timeout or something else?

Thanks,

**Comment by c6fc** [comment]
1. Was it raw or gzip?
2. What is the total size? If it's Gzip, include raw and compressed sizes
3. When you say 'stopped processing', do you just mean the spinner on the file management page, or something else?

**Comment by bzekanovic** [comment]
1. gzip
2. 970MB gzip  and raw 1.7GB.  
3. Yeah, spinner in file manager page. I left it overnight and it was still sitting in pending state.

**Comment by c6fc** [comment]
Can you please check the logs of the compression_pipe lambda function and see if there are any errors?

**Comment by bzekanovic** [comment]
I'm seeing below error consistently 

2022-04-08T14:48:48.046Z	<ID>	ERROR	Invoke Error 	{
    "errorType": "ReferenceError",
    "errorMessage": "copy is not defined",
    "stack": [
        "ReferenceError: copy is not defined",
        "    at Runtime.exports.main [as handler] (/var/task/main.js:118:3)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}

**Comment by c6fc** [comment]
Cool, that helps. I see the issue and will work towards a solution. In the meantime, if you upload it raw, it should bypass the bug. Let me know if you have issues with that workaround

**Comment by bzekanovic** [comment]
Thank you!

**Comment by c6fc** [comment]
I patched this and verified that it works. There's still a known issue with very large files, and I plan to rewrite this piece again to address it, but this issue is resolved for now.
