### ISSUE TITLE
Start Campaign Error - UnauthorizedOperation

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#51]
Getting below error when starting a new campaign. Can you replicate this on your side since nothing changed on our side when it comes to deployment. 

![image](https://user-images.githubusercontent.com/16389468/166504704-61e6c2ef-0078-4a61-8104-3fa4e1f83d6b.png)

**Comment by c6fc** [comment]
Is there any more to that error? Like a stack trace?
Also, which Lambda function is this?

**Comment by c6fc** [comment]
My campaign started just fine. Feel free to drop into Discord if you want help

**Comment by bzekanovic** [comment]
I'm going to dive more into this and see what could have caused it. We did deploy policy to restrict regions on AWS account to US only, but I'm not sure if that would cause this issue. I'll start testing this more in my sandbox environment and I can re-open this issue if you don't have any other ideas. thx

See below log output from CloudWatch. 

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "UnauthorizedOperation: You are not authorized to perform this operation.",
    "reason": {
        "errorType": "UnauthorizedOperation",
        "errorMessage": "You are not authorized to perform this operation.",
        "code": "UnauthorizedOperation",
        "message": "You are not authorized to perform this operation.",
        "time": "2022-05-03T17:19:36.675Z",
        "requestId": "db2876cc-46d4-4d24-9bb5-dff9571fcbe8",
        "statusCode": 403,
        "retryable": false,
        "retryDelay": 20.205925162690484,
        "stack": [
            "UnauthorizedOperation: You are not authorized to perform this operation.",
            "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/ec2.js:50:35)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: UnauthorizedOperation: You are not authorized to perform this operation.",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}

**Comment by c6fc** [comment]
SCPs are definitely modifications on your side. Given that you're getting auth failures across multiple accounts, this is extremely likely to be the cause.

**Comment by bzekanovic** [comment]
I think its safe to close this one. thx
