### ISSUE TITLE
NPK Instance Region Admin Settings

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#58]
Allow admins to configure which regions NPK can utilize when users are selecting ec2 instance. We tried to implement this via AWS policy, but that broke some stuff with NPK campaign starting and NPK terraform code deployment. More info can be found here https://github.com/c6fc/npk/issues/51

**Comment by c6fc** [comment]
I'm not terribly eager to add more complexity to the challenges users already face with instance availability and quota. If your org wants help with a custom integration or supplemental controls, I'm happy to consult with them on how to do it, but I don't think this is a good feature for the project overall.
