### ISSUE TITLE
WPA / WAP2 Hash File Issue

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#6]
Running into error below when trying to create campaign with hash type wpa/wpa2 hccapx file. 

  ERROR    Unknown parameter type "require". Must be "request_descriptors", "response_descriptors", "request_parameters" or "response_parameters".

![image](https://user-images.githubusercontent.com/16389468/127927860-8111e58b-8447-4dfd-9851-3b2161ea95fe.png)

**Comment by bzekanovic** [comment]
@c6fc  

Are you able to replicate this on your side? I was able to replicate this with Hashcat hccapx example file.

**Comment by c6fc** [comment]
I'll test it out today and see what's up.

**Comment by bzekanovic** [comment]
Following up to see if you got a chance to look over issue above. thx

**Comment by c6fc** [comment]
I believe I've resolved the problem in the api_rewrite branch. I'll continue testing and update when it's ready for use.

**Comment by c6fc** [comment]
@bzekanovic please checkout and deploy the 'dev' branch to and let me know if this fails to fix it.

**Comment by bzekanovic** [comment]
Will let you know how it goes. thx

**Comment by c6fc** [comment]
Fixed in v2.5 5f40f04
