### ISSUE TITLE
CloudShell Improvement

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#60]
Please provide option for end users to specify if they want to just pull down current config or load current config and pull latest version of NPK when executing source <(curl https://npkproject.io/cloudshell_install.sh).

**Comment by c6fc** [comment]
Can you clarify what you're asking for? 'pull down' and 'load' current config sound synonymous to me (and are default behavior), and the one-liner already pulls the latest version...

**Comment by bzekanovic** [comment]
As of right now running source <(curl https://npkproject.io/cloudshell_install.sh) will upgrade current NPK to latest version each time you run it. This means if I want to make small config change to our current deployment I have to do full upgrade of NPK. What I'm asking is for source <(curl https://npkproject.io/cloudshell_install.sh) prompt user if user wants to upgrade NPK to latest version before it executes terraform code.

**Comment by c6fc** [comment]
There's currently no way for CloudShell to know what version you're running, and trying to persist, track, or diff commits would be a huge undertaking.

If you want to pin your deployment to a specific commit, I'd recommend that you fork NPK and use a deployment script that references your own fork.

**Comment by bzekanovic** [comment]
Sounds good. thx
