### ISSUE TITLE
Hashes won't Ingest 

### ISSUE THREAD

**Issue by ECGBQ** [c6fc/npk#61]
Trying to run NTLM hashes.

Did as instructed with just the hash and one per line.

![2022-06-16_12-42-20](https://user-images.githubusercontent.com/96191592/174130944-188dd3c9-8124-4d4b-936c-8a1d057dbd78.jpg)

**Comment by c6fc** [comment]
The hash count is populated by hashcat after the campaign is started. Click 'start'

**Comment by c6fc** [comment]
"Nodes may still be starting"

Wait until they've started.

**Comment by c6fc** [comment]
Limits are granted for vCPUs, not instance count. A g4dn.xlarge uses 4 vCPUs per instance, which means a limit of 8 will allow to run two instance simultaneously.

g5 instances aren't available in us-east-2

**Comment by ECGBQ** [comment]
Ok, thanks for all your help!
