### ISSUE TITLE
Possibly incorrect hashcat syntax

### ISSUE THREAD

**Issue by Donovoi** [c6fc/npk#62]
Absolutely love what you are doing so please keep it up!

I had a look at the hashcat command being used:
`./hashcat/hashcat.bin --quiet -O 4 -m 1600 -a 0  hashes.txt wordlist/NetgearKiller.7z wordlist/Top-10k.7z wordlist/Top-1M.7z wordlist/acdc.7z wordlist/probable-v2-wpa-top4800.7z wordlist/rockyou.7z`

From what I understand `-O` is just a switch and does not take any arguments, but you have `4` straight after it. Unless I'm completely missing something, are you meaning `-O -w 4`?

That would make more sense to me. 

Let me know what you think.

**Comment by c6fc** [comment]
Where did you see this?

**Comment by c6fc** [comment]
This has been addressed in 'dev' - please test and let me know if it's resolved.

**Comment by Donovoi** [comment]
Looks good thank you!

![Screenshot_20220704-041626_Chrome.jpg](https://user-images.githubusercontent.com/24791115/177052311-91e85ad1-a259-4885-a0ab-2800ed7484a0.jpg)

**Comment by c6fc** [comment]
Pushed to main
