### ISSUE TITLE
How do I get instances to show up from multiple Regions?

### ISSUE THREAD

**Issue by ECGBQ** [c6fc/npk#64]
Hi, I got approved for 4 spot instances in us-west-2 and want to use the G5 but they are not showing up when trying to start a new campaign. I re-ran the install script after they approved it. Is there something else I need to do?

![image](https://user-images.githubusercontent.com/96191592/174851662-bf554d96-bb35-46de-9b60-872ebeda5120.png)

In the wiki, I see you can choose from multiple Regions and would like mine set up the same.

![image](https://user-images.githubusercontent.com/96191592/174851988-2174cb7f-c5db-4503-903d-a5bb8523ad67.png)

**Comment by c6fc** [comment]
Shift refresh

**Comment by c6fc** [comment]
1. Limit isn't granted for instances. It's granted for vCPU.
2. Limits are granted per-region. If you want more than one region, ask for limit increases in other regions.
3. After limits are raised and you re-run the one-liner, you may need to shift+refresh on the campaign management page to pick up the changes.

**Comment by ECGBQ** [comment]
Thanks! It worked.

***@***.***

Eric Conklin
Associate Security Analyst

P (614) 947-5257
F (614) 947-5457
C (734) 735-2554


GBQ Partners LLC
230 West Street, Suite 700
Columbus, OH 43215


***@***.******@***.***>
www.gbq.com<https://gbq.com/>

Stay connected: Facebook<https://www.facebook.com/pages/columbus-oh/gbq/339020273933> | Twitter<https://www.twitter.com/gbq_llc> | LinkedIn<https://www.linkedin.com/company/gbq-partners> | Online Bill Payment<https://gbq.com/make-a-payment/>

Note: Our offices will be closed July 1-8, 2022.
