### ISSUE TITLE
Dictionary + rules produces different results than dictionary alone.

### ISSUE THREAD

**Issue by ECGBQ** [c6fc/npk#65]
I have a file of 97 hashes that I uploaded and a file of 41 passwords that are all legit, and they all crack, but adding a rule set file to it only cracked 1 out of 97.

**Comment by c6fc** [comment]
Can you provide screenshots of the campaign configurations for both?

**Comment by ECGBQ** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/96191592/175390837-ddc24630-914a-4366-b9ea-51f2ce99fd10.png)

![image](https://user-images.githubusercontent.com/96191592/175392209-e886c293-ce51-4b1b-b192-b615c131f94b.png)

This will one crack 1 out of 97 with this config


![2022-06-23_16-16-38](https://user-images.githubusercontent.com/96191592/175391985-7478010b-e93a-4648-8361-f57fa38fe7ca.jpg)

**Comment by c6fc** [comment]
I mean from the 'Manage Campaigns' view, so that I can see the actual settings that were used.

**Comment by c6fc** [comment]
Also - if you run it locally with the same dictionary and rule file, does it behave the same way? If the rules file doesn't include an entry for the raw dictionary entry, it won't try the raw dictionary entry.

**Comment by ECGBQ** [comment]
![2022-06-23_16-27-43](https://user-images.githubusercontent.com/96191592/175393575-dd97b159-0ada-40c7-880f-6968b4559f6b.jpg)

![2022-06-23_16-30-39](https://user-images.githubusercontent.com/96191592/175394040-1176b17f-2108-48cb-aaef-c1189fdf4ce1.jpg)

**Comment by c6fc** [comment]
Does your megaUniq rule file have a 'nothing' or 'passthrough' entry?

https://hashcat.net/wiki/doku.php?id=rule_based_attack

**Comment by ECGBQ** [comment]
^:
^: ^<
^: ^=
^: ^>
^: ^_
^: ^-
^: ^:
^: ^!
^+ $%
^+ $+
^+ $+
^+$+
^+
:
:
[
[^=
[^-
[^,
[^;

**Comment by c6fc** [comment]
1. Does the same thing happen when running locally with and without the rule file?
2. Does the cracked_hashes for the second campaign actually only contain a single entry?

**Comment by c6fc** [comment]
Also, you should consider joining the discord channel. We can troubleshoot more quickly there.

**Comment by ECGBQ** [comment]
When running locally it works. I will try to get on the discord channel now.

**Comment by ECGBQ** [comment]
Ah, my company is blocking me from going there. I will jump on when I get home. How late will you be around today?

**Comment by c6fc** [comment]
What version of hashcat are you running locally, and what commands are you using?

You can look at the instance logs under 'file management' to see what parameters are being used with Hashcat, to make sure you're running it the same.

**Comment by ECGBQ** [comment]
Hashcat -m 1000 /path/to/ntds /path /to/wordlist -r /path/to/rulesfile

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by c6fc** [comment]
Use the parameters and arguments from the instance logs. If it behaves the same, it's an issue with Hashcat, not with NPK

**Comment by ECGBQ** [comment]
I tried a bunch of different rule sets. Whenever a rule set is applied, all it will crack is the null hash. It works perfectly fine with no rule set. I can get on Discord today if you can take a look.

Thanks,

***@***.***

Eric Conklin
Associate Security Analyst

P (614) 947-5257
F (614) 947-5457
C (734) 735-2554


GBQ Partners LLC
230 West Street, Suite 700
Columbus, OH 43215


***@***.******@***.***>
www.gbq.com<https://gbq.com/>

Stay connected: Facebook<https://www.facebook.com/pages/columbus-oh/gbq/339020273933> | Twitter<https://www.twitter.com/gbq_llc> | LinkedIn<https://www.linkedin.com/company/gbq-partners> | Online Bill Payment<https://gbq.com/make-a-payment/>

Note: Our offices will be closed July 1-8, 2022.

**Comment by c6fc** [comment]
I just tested it myself - ran two NTLM campaigns with RockYou, with and without OneRuleToRuleThemAll ruleset, and got 3/4 hashes cracked on both.

Can you pull the instance log for the campaign with the rule list and DM it to me?

**Comment by ECGBQ** [comment]
[output.txt](https://github.com/c6fc/npk/files/8993575/output.txt)

**Comment by c6fc** [comment]
I see no issues with the output log. Can you send me the hashlist and point me at the dictionary you're using so I can test it myself?

**Comment by ECGBQ** [comment]
sent

**Comment by ECGBQ** [comment]
I can only get it to work by uploading all the passwords I cracked with my coworker's on-prem cracker as the wordlist. If I use that wordlist with all of the rules, it doesn't work.

**Comment by c6fc** [comment]
I just used this hashlist with RockYou and OneRuleToRuleThemAll and cracked 25 of the 97 unique hashes. It seems to be working fine.

**Comment by c6fc** [comment]
![results](https://user-images.githubusercontent.com/143415/175995290-888f4062-f4b8-4c62-b911-1fd2eb7de070.png)

Without rules on the top, with rules on the bottom. The results are exactly what I'd expect.

**Comment by ECGBQ** [comment]
Ok, I got the same results. When using those together. I'll mess around with it more. Thanks for all your help.

**Comment by ECGBQ** [comment]
If you run a rule set with a dictionary list it will still run through that word list right before applying any rules correct?

**Comment by c6fc** [comment]
Ok, sounds like it's an issue with your rule list, then. I'll close this out for now. Feel free to reopen if you discover that this isn't the case.

As for your question about rules, Hashcat won't attempt the raw dictionary candidate before applying rules. The rule list needs to have a passthrough rule if you want the unmodified candidate to be checked. NPK used to add one to avoid this confusion, but I removed that functionality quite a while ago to keep the behavior the same as Hashcat.

I hope this helps.
