### ISSUE TITLE
How to use an existing potfile

### ISSUE THREAD

**Issue by LuigiPolidorio** [c6fc/npk#69]
I already have a large pot file with a lot of cracked hashes, and I want to use it with NPK, sharing it with all campaigns to increment the potfile and to avoiding cracking the same hash twice, there is a way I could do it?

**Comment by c6fc** [comment]
There is not. Potfiles are best used outside of NPK since even the weakest hardware can make use of it. My recommendation has always been to check hashes against your potfile yourself, remove any known hashes before starting a campaign, and leave just the cracking to NPK.
