### ISSUE TITLE
Error: Error parsing response JSON.  

### ISSUE THREAD

**Issue by burns0x01** [c6fc/npk#7]
Hello,

We are on the newest version of NPK and have no errors during install, but we have this error when submitting campaigns and starting them. Very rarely will the campaigns will submit successfully and some times they will start, but the error happens more often then not. 

This was with a a custom wordlist (crackstation) and 450 NTLM hashes. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/89157295/129949518-73950fd9-410a-436f-ab8d-be99ca8e9328.png)

Let me know what other info you need!

**Comment by Snakemaster6909** [comment]
I confirm I am getting the same issues

**Comment by bzekanovic** [comment]
@c6fc  

Did you get a chance to look over this one?

**Comment by bzekanovic** [comment]
> @c6fc
> 
> Did you get a chance to look over this one?

I'm seeing this in my CloudWatch 
![image](https://user-images.githubusercontent.com/16389468/131926151-5956e3d8-1413-4737-a06b-97af2eeb373f.png)

**Comment by c6fc** [comment]
I've verified that I can reproduce the error. I'm working on a fix that will involve some substantial changes to the API structure, but that should also MASSIVELY improve readability and maintainability. It'll be tracked under a new branch for the moment, and merged into dev and prod once it's been tested. Keep an eye out.

**Comment by c6fc** [comment]
I'm trying to replicate this in dev, but I can't recreate it. @bzekanovic in the screenshot you provided it's clear that it's breaking down while processing rule files, but if I set it up a campaign to use the default ones, they work fine.

Could you show me the campaign configuration you're using when you get this error?

**Comment by bzekanovic** [comment]
@c6fc 

I was able to resolve this issue by upgrading my deployment to your current main branch. This issue was occurring with main branch from Coalfire repo.  I'm not sure if this helps on what could have caused issue. 

thx

**Comment by c6fc** [comment]
Fixed in v2.5 5f40f04
