### ISSUE TITLE
Unable to Launch instances (launchSpecUnusable)

### ISSUE THREAD

**Issue by 0xlazY** [c6fc/npk#70]
Hi,
I get this error when trying to launch any type of instances:

Info (launchSpecUnusable) :
**p2.xlarge, ami-0e02647cb673cb89a, Linux/UNIX, eu-central-1c, requested instance type is not supported in the requested Availability Zone**
Error (spotFleetRequestConfigurationInvalid) :
**p2.xlarge, ami-0e02647cb673cb89a, Linux/UNIX: We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested**

I upgraded my quotas and my p2 instances limits and can launch a p2.xlarge (on ami-0e02647cb673cb89a) instance manually on the EC2 console.
Is this a eu-central-1 region problem ? 

Thanks

**Comment by c6fc** [comment]
That's normal. Each availability zone reports it's own status individually,
and availability or support for an instance type in one zone doesn't impact
the spot fleet overall.

**Comment by c6fc** [comment]
It's not a fatal error. If other availability zones are failing for
different messages, let me know, but that one is normal. Just be patient
and allow other availability zones to attempt the spot fleet.

**Comment by 0xlazY** [comment]
same error on eu-west-1

p2.xlarge, ami-0cabec8b9e9da9cd5, Linux/UNIX: There is no Spot capacity available that matches your request.
then
Repeated errors have occurred processing the launch specification "p2.xlarge, ami-0cabec8b9e9da9cd5, Linux/UNIX, eu-west-1c while launching spot instance". It will not be retried for at least 13 minutes. Error message: There is no Spot capacity available that matches your request. (Service: AmazonEC2; Status Code: 500; Error Code: InsufficientInstanceCapacity; Proxy: null)

**Comment by c6fc** [comment]
That's a very different error, and that's one that will cause failures. As it says, it means there's no spot instances of that type available right now. Try a different instance type, instance family, different region, or try again later.

**Comment by 0xlazY** [comment]
This can't be right, it's saying that in 2 region, with every instance type, and I can launch the exact instance manually on my aws console.
