### ISSUE TITLE
Wordlist in to_process folder after upload

### ISSUE THREAD

**Issue by Khatcode** [c6fc/npk#73]
Hey I just uploaded rockyou2021 to my npk. Is this normal? Do I need to run a command to process this file so I can see it in my word lists?
![image](https://user-images.githubusercontent.com/68708968/189013289-7cb1857d-e895-4ac4-90f7-e5c4f1338281.png)

**Comment by c6fc** [comment]
Large files take a long time to process - on average around 5 minutes per GiB. It looks like it's only been ~1.5 hours, so give it some time. So far you're still within 'normal'.

**Comment by Khatcode** [comment]
Alright. Thank you I will close the issue.
