### ISSUE TITLE
Unable to parse response as json

### ISSUE THREAD

**Issue by Luct0r** [c6fc/npk#80]
Having the same problem from https://github.com/Coalfire-Research/npk/issues/4

New install, tried Chrome and Firefox, and the campaign does not get created after the error. Also same thing where the response is blank.

I went in to check out the Lambda logs like you mentioned in that issue, but I don't see the "proxy_api_handler" function? Any thoughts?

Thanks!

**Comment by c6fc** [comment]
Don't use the coalfire-research one. It's massively outdated. Use the one-liner from this repo to deploy.

**Comment by Luct0r** [comment]
Hmm I'm fairly confident I did...but let's just assume I was an idiot and used the one from CF repo. Do I have to do a full tear down or?

**Comment by Luct0r** [comment]
I mentioned that issue since it's what came up when googling the error.

**Comment by c6fc** [comment]
delete it and install the one from this repo

**Comment by c6fc** [comment]
If you're certain that you installed the version from this repo, check the Cloudwatch logs for the `create_campaign` lambda function for the error, and paste it here

**Comment by Luct0r** [comment]
Hmm okay looks like it was something in my `npk-settings.json`, I reduced the `campaign_max_price` and the `campaign_data_ttl`, and added SSO.

Left SSO, removed the other two and it's fine....oh could it be putting quotes around the `campaign_data_ttl` value?

**Comment by Luct0r** [comment]
Well don't be an idiot I guess and put quotes around a number/int value....
Sorry for the trouble
