### ISSUE TITLE
terraform: Error installing provider "aws": openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by jstigerwalt** [c6fc/npk#9]
I was presented with a terraform error when running the deploy.sh script from the docker image:

`Error installing provider "aws": openpgp: signature made by unknown entity`

This seems to be due to the current version you are using in the docker image. I was able to get this fixed by running the following command and then re-running the deply.sh script:
`terraform init -verify-plugins=false`

A fix would be to update terraform to a newer version that has the newly updated GPG keys.

I found this information in the following URL:
https://stackoverflow.com/questions/67368339/error-installing-provider-aws-openpgp-signature-made-by-unknown-entity

**Comment by c6fc** [comment]
Interesting. Supposedly this is fixed in 11.15 (sans '-oci'). I'll test it and update the Dockerfile.

**Comment by c6fc** [comment]
I pushed 5a3664b to the dev branch to change the pinned terraform version in Docker. It worked out of the box for me end-to-end. Give it a shot and let me know if you encounter any further issues.

**Comment by c6fc** [comment]
This is fixed in Terraform 0.15, which is now used as the primary version in the Dockerfile as of 5f40f04
